[package]
name = "miryam"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk4 = { version = "0.11", features = ["v4_6"] }
gtk4-layer-shell = "0.8"
rand = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1"
anyhow = "1"
chrono = "0.4"
poppler-rs = "0.26.0"
cairo-rs = "0.22.0"
