[[group]]
phrases = [
  "CPUは平静です",
  "そのターミナル、昨日から開いていませんか",
]

[[group]]
time = ["morning"]
phrases = ["おはようございます"]

[[group]]
time = ["daytime"]
phrases = ["Slackを見る時間ではないでしょうか"]

[[group]]
time = ["evening"]
phrases = ["少し休憩してもよいのでは"]

[[group]]
time = ["night"]
phrases = ["夜更かしですね"]

[[group]]
uptime_hours = 4
phrases = ["そろそろ休憩しませんか"]
